language: ruby
rvm:
  - 2.5.1
env:
  matrix:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec webpacker:compile
  - bundle exec rspec
before_install:
  - export TZ=US/Mountain
