# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
NEW_RELIC_LICENSE_KEY: cf47f362416f860c114aa811f66ce8666d2d029e
DATABASE_URL: 'postgres://root:mysecretpassword@db:5432/baseball_13_leagues?encoding=utf8&pool=5&timeout=5000'
RAILS_ENV: 'development'
PORT: 3000
