default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: baseball_13_leagues_development

test:
  <<: *default
  database: baseball_13_leagues_test

production:
  <<: *default
  database: baseball_13_leagues_production
  username: baseball_13_leagues
  password: <%= ENV['BASEBALL_13_LEAGUES_DATABASE_PASSWORD'] %>
