development:
  url: <%= ENV['DATABASE_URL'].gsub('?', 'development?') %>

test:
  url: <%= ENV['DATABASE_URL'].gsub('?', 'test?') %>

production:
  url: <%= ENV['DATABASE_URL'].gsub('?', 'production?') %>
